### PR TITLE
feat: pull to refresh

### PR DESCRIPTION
**Pull request by sdip15fa**
Tested on android only.

### CODE REVIEW

**Comment by chunlaw** [comment]
It is a must to test in iOS for such cross-platform app.

**Comment by sdip15fa** [comment]
I am not sure if it will work on ios after testing with a simulator. However, it is not going to cause any bugs.

**Comment by sdip15fa** [comment]
After further testing, it should work on ios.

**Comment by chunlaw** [comment]
The issue should be resolved by 
[onContentProcessDidTerminate](https://github.com/hkbus/mobile-bus-app/blob/4b49d20ebbdbec4b84284ac4c1c58ffbfefe4ace/App.tsx#L245-L259)

**Pull request closed without merging**
